# Setup
title:        killf的个人博客
tagline:      
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       killf
  url:        http://www.killf.info

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown